# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/ubuntu2204"

  # a synced folder to share info between the vms
  config.vm.synced_folder './', '/vagrant',
    type: 'nfs',
    nfs_udp: false,
    nfs_version: 4

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
  SHELL

  config.vm.define "alagacheS" do |control|
    control.vm.hostname = "alagacheS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider :libvirt do |libvirt|
      libvirt.memory = "1024"
    end


    # we need k3s installed as a server
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san 192.168.56.110 --node-ip 192.168.56.110" K3S_NODE_NAME="$HOSTNAME" K3S_KUBECONFIG_MODE="644" sh -
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/
    SHELL

  end

  config.vm.define "alagacheSW" do |control|
    control.vm.hostname = "alagacheSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider :libvirt do |libvirt|
      libvirt.memory = "1024"
    end


    # we use K3S_URL to tell installer to set it as agent
    # use the server token file in install
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.111" K3S_URL="https://192.168.56.110:6443" K3S_TOKEN_FILE="/vagrant/node-token" sh -
    SHELL
  end


end
