# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/jammy64"
  # update box / less download with p1a modification
  config.vm.box = "debian/bookworm64"

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
  SHELL

  config.vm.define "alagacheS" do |control|
    control.vm.hostname = "alagacheS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "alagacheS"]
      v.memory = "4096"
    end

    # need to expose a folder with a copy of server token
    config.vm.synced_folder ".", "/vagrant"

    # we need k3s installed as a server
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san 192.168.56.110 --node-ip 192.168.56.110 --node-external-ip 192.168.56.110" K3S_NODE_NAME="$HOSTNAME" K3S_KUBECONFIG_MODE="644" sh -
      kubectl apply -f /vagrant/confs/simple-kustomisation.yaml
    SHELL

  end

end
